export const BaseEnvConfig = {
  PORT: 'PORT',
  TOKEN_EXPIRATION_TIME: 'TOKEN_EXPIRATION_TIME',
  TOKEN_SECRET: 'TOKEN_SECRET',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRATION_TIME: 'REFRESH_TOKEN_EXPIRATION_TIME',
  CONNECTION_STRING: 'CONNECTION_STRING',
};
